name: servisin_aja
description: "Multi-Vehicle Service Booking App"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.3
  google_fonts: ^8.2.1
  intl: ^0.20.3
  ionicons_plus: ^0.2.5

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
